name: Test

on:
  workflow_dispatch:
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm ci

    - name: Compile
      run: npm run build

  GetChangeDetails:
    needs: build
    runs-on: ubuntu-latest
    name: Servicenow Get Change Details

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Servicenow Get Change Details
        uses: ServiceNow/servicenow-devops-get-change@2.0.0
        id: get
        with:
          devops-integration-user-name: ${{ secrets.gowthamivanguri }}
          devops-integration-user-password: ${{ secrets.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 }}
          instance-url: ${{ secrets.https://dev250872.service-now.com }}
          context-github: ${{ toJSON(github) }}
          tool-id: ${{ secrets.449cda0ac3011210848ff44ed4013165 }}
          change-details: '{"pipeline_name":"maheshganji/custom-action-get/CustomActionGetWorkflow","stage_name":"ServiceNow Change Approval","build_number":"3732116819"}'
      - name: Output of GetChangeDetails
        run: echo "The Status of Update Change Request Details => ${{ steps.get.outputs.change-request-number }}"
